#! /bin/sh

#-- AutoStart applications. --#

xsetroot -cursor_name left_ptr		# To Show Mouse Pointer correctly.
pgrep -x sxhkd > /dev/null || sxhkd & # Loading Key Bindings
nm-applet &		# Loading Network Tray
pamac-tray &	# Loading System Tray
picom &			# Compositor
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Loading gnome-keyring for password popup.
blueman-applet &	# Lodaing Bluetooth Tray Icon.

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &
sed -i 's/size:\ 12/size:\ 8/g' $HOME/.config/alacritty/alacritty.yml
$HOME/bin/mirror.sh

bspc config merge_overlapping_monitors   true
bspc config border_width         0
bspc config window_gap          12
# bspc config top_padding			32
# bspc config bottom_padding		32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Teams desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

